
var products = [{
  "listing_id": 0001,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/arturo_fuente.jpg'>",
  "productThumb": "<img src='images/thumbs/arturo_fuente.jpg'>",
  "productTitle": "Arturo Fuente: Opus X Lost City",
  "productDescription": "Lost City remains full-bodied from head to foot with a toasty character throughout. Perfectly blended, you will find each and every Lost City smokes, burns and tastes the same from box to box as they expel earthy nuances with hints of spice. Packed full of Dominican long leaves, OpusX Lost City is one of the rarest blends ever released to date. ",
  "pairing": "Cranberry-Orange",
  "productPrice": 22.00,
  "Country of Origin": "Cuba",
  "quantity": 1,
}, {
  "listing_id": 0002,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/Cohiba.jpg'>",
  "productThumb": "<img src='images/thumbs/Cohiba.jpg'>",
  "productTitle": "Cohiba: Double Corona LE",
  "productDescription": "Special Guest Review:  From the beginning, I knew I had something special. The light-up was all roasted wood and hickory. A tiny hint of sweetness to linger on your lips and palette. The second third gave me that stinging sensation that I love. Perfect with a nice coffee chaser. The final third, I hate to admit, was a bit too strong almost, particularly towards the last hit. The first two thirds made it worth it all however.",
  "pairing": "Chocolate Chip",
  "productPrice": 25.00,
  "Country of Origin": "Cuba",
  "quantity": 1,
}, {
  "listing_id": 0003,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/davidoff_zino.jpg'>",
  "productThumb": "<img src='images/thumbs/davidoff_zino.jpg'>",
  "productTitle": "Davidoff: Zino",
  "productDescription": "Editorial review: I was hoping to experience something like an Opus X kick with a complexity that could match a high quality Cuban cigar. First puffs brought a wonderful tobacco flavor that was in the background throughout the smoke. There were nice woody and peppery notes that didn't save the day. Overall, a mild, simple, medium-bodied cigar.",
  "pairing": "Gingersnap",
  "productPrice": 20.00,
  "Country of Origin": "Cuba",
  "quantity": 1,
}, {
  "listing_id": 0004,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/macanudo.jpg'>",
  "productThumb": "<img src='images/thumbs/macanudo.jpg'>",
  "productTitle": "Macanudo: Churchill Limited",
  "productDescription": "Editorial review: The Macanudo Vintage Maduro 1997 opened somewhat dry with a nuttiness layering the front of my palate. Once over the shoulder the first third of this smoke displayed nice spicy, woodsy, cedary characters to go along with the nuttiness. This very slow burning cigar gave part to a thin white smoke and extreme white ash. What was very interesting is the taste the wrapper leaf was leaving on my lips. A very sweet, sugary taste almost like a clove cigarette… interesting.",
  "pairing": "Carrot Cake",
  "productPrice": 20.00,
  "Country of Origin": "Cuba",
  "quantity": 1,
}, {
  "listing_id": 0005,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/montecristo.jpg'>",
  "productThumb": "<img src='images/thumbs/montecristo.jpg'>",
  "productTitle": "Montecristo: No 1",
  "productDescription": "The flavour of this cigar is what really blew me away. Right off the bat I was getting nice creamy cappuccino smoke. There were hints of cedar on the palate reminiscent of the traditional Montecristo style however this cigar was much more committed to the creamy coffee flavours. The date for this box is from 2008 making it a 3 and a half year old box. I believe these cigars are at their prime smoking time right now. The youthful desire of the tobacco has been tempered by aged creating a rich harmony of flavours; a welcomed improvement from some of the younger Montecristos I smoked while in Cuba. The finish is smooth with noticeable leather. At this stage I would consider this cigar medium bodied. This is a change from the full-bodied pungent Cubans I normally turn to; however this cigar is nice in a subtler way.",
  "pairing": "Red Velvet",
  "productPrice": 20.00,
  "Country of Origin": "Cuba",
  "quantity": 1,
}, {
  "listing_id": 0006,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/partagas.jpg'>",
  "productThumb": "<img src='images/thumbs/partagas.jpg'>",
  "productTitle": "Partagas: No 4",
  "productDescription": "The flavour of this cigar is what really blew me away. Right off the bat I was getting nice creamy cappuccino smoke. There were hints of cedar on the palate reminiscent of the traditional Montecristo style however this cigar was much more committed to the creamy coffee flavours. The youthful desire of the tobacco has been tempered by aged creating a rich harmony of flavours; a welcomed improvement from some of the younger Montecristos I smoked while in Cuba. The finish is smooth with noticeable leather. At this stage I would consider this cigar medium bodied. This is a change from the full-bodied pungent Cubans I normally turn to; however this cigar is nice in a subtler way.",
  "pairing": "Multigrain",
  "productPrice": 20.00,
  "Country of Origin": "Dominican Republic",
  "quantity": 1,
}, {
  "listing_id": 0007,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/pucnh.jpg'>",
  "productThumb": "<img src='images/thumbs/punch.jpg'>",
  "productTitle": "Punch: Selectione Limited",
  "productDescription": "The flavors deliver on the sweet promise of the pre-light aroma. They are nutty, slightly earthy, and have a hint of hay. There is something sugary here, but it is not overwhelming. During the middle third, the flavors move even deeper into earthy terrain, with the hay becoming more prominent—maybe the hay really is the main source of the sweetness. There is also a little spice, but it is very faint. In the final third, most of these flavors fall back, and I get a bakery flavor that reminds me of cake or maybe a cinnamon roll.",
  "pairing": "Strawberry and Cream",
  "productPrice": 20.00,
  "Country of Origin": "Honduras",
  "quantity": 1,
}, {

  "listing_id": 0008,
  "category_id": "Cigars",
  "productImage": "<img src='images/store_large/Romeo_y_Jullieta.jpg'>",
  "productThumb": "<img src='images/thumbs/Romeo_y_Jullieta.jpg'>",
  "productTitle": "Romeo y Julieta: Churchill",
  "productDescription": "There are light aromas of tobacco and citrus at cold.This is starting very lightly but it is a treat. The smoke seems to be thin in the mouth but it is very tasty. The smoke is also pungent and sweet smelling. There are a lot of sweet flavors. I can taste honey, caramel and some coffee. The after taste is very clean and short. There aren’t any flavors left in mouth.The caramel flavors are really well defined. I am really enjoying this.The second part is very similar to the first one. It changes slightly and adds some toasted bread flavors. The sweet honey/caramel aroma is turning into a strong defined sweet cherry flavor. That’s pretty unexpected but quite good. There is more smoke and still no aftertaste lingering in the mouth. Past the halfway point, I can feel the nicotine build up. The body is light-medium.",
  "pairing": "Blueberry Coconut",
  "productPrice": 20.00,
  "Country of Origin": "Cuba",
  "quantity": 1,
}, {
  "listing_id": 0009,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/blueberry_coconut.jpg'>",
  "productThumb": "<img src='images/thumbs/blueberry_coconut.jpg'>",
  "productTitle": "Blueberry Coconut",
  "productDescription": "Remember the banana coconut muffins?  They may be my most favorite muffin ever.  These are a close second, but I don’t love blueberries as much as bananas. Obviously – why would I love something that is full of antioxidants? It’s basically against my rules.  But the blueberry-coconut combo is pretty darn delicious.",
  "pairing": "Romeo y Julieta: Churchill",
  "productPrice": 6.00,
  "Country of Origin": "Denmark",
  "quantity": 1,
}, {
  "listing_id": 0010,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/cranberry_orange.jpg'>",
  "productThumb": "<img src='images/thumbs/cranberry_orange.jpg'>",
  "productTitle": "Cranberry-Orange",
  "productDescription": "We believe that good bread makes people happy. That’s why we’re always dreaming up new ways to make bread more delicious. We hope you enjoy our latest creation – Morning Muffins – as much as we do.They're delicious toasted, topped with your favorite preserves, or just by themselves - the perfect portable breakfast!Morning Muffins are crafted with care in small batches, and contain absolutely nothing artificial! Morning Muffins Cranberry Orange Buns are all-natural healthy grain buns full of sweet dried cranberries and fresh oranges.",
  "pairing": "Arturo Fuente: Opus X Lost City",
  "productPrice": 6.00,
  "Country of Origin": "Denmark",
  "quantity": 1,
}, {
  "listing_id": 0011,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/ginersnap.jpg'>",
  "productThumb": "<img src='images/thumbs/ginersnap.jpg'>",
  "productTitle": "Gingersnap",
  "productDescription": "We believe that good bread makes people happy. That’s why we’re always dreaming up new ways to make bread more delicious. We hope you enjoy our latest creation – Morning Muffins – as much as we do.They're delicious toasted, topped with your favorite preserves, or just by themselves - the perfect portable breakfast! Morning Muffins are crafted with care in small batches, and contain absolutely nothing artificial! Morning Muffins Gingersnap are all-natural healthy grain buns full of ginger essence and delicious spices..",
  "pairing": "Davidoff: Zino",
  "productPrice": 6.00,
  "Country of Origin": "Denmark",
  "quantity": 1,
}, {
  "listing_id": 0012,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/strawberry_cream.jpg'>",
  "productThumb": "<img src='images/thumbs/strawberry_cream.jpg'>",
  "productTitle": "Strawberry and Cream",
  "productDescription": "Along with watching Wimbledon and enjoying a pitcher of Pimm's, they are the essential ingredients for a traditional British summer.  the perfect portable breakfast!Morning Muffins are crafted with care in small batches, and contain absolutely nothing artificial!",
  "pairing": "Punch: Selectione Limited",
  "productPrice": 6.00,
  "Country of Origin": "England",
  "quantity": 1,
}, {
  "listing_id": 0013,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/chocolate_chip.jpg'>",
  "productThumb": "<img src='images/thumbs/chocolate_chip.jpg'>",
  "productTitle": "Chocolate Chip",
  "productDescription": "We believe that good bread makes people happy. That’s why we’re always dreaming up new ways to make bread more delicious. We hope you enjoy our latest creation – Morning Muffins – as much as we do.They're delicious toasted, topped with your favorite preserves, or just by themselves - the perfect portable breakfast! Morning Muffins are crafted with care in small batches, and contain absolutely nothing artificial! Morning Muffins Chocolate Chip are made from the finest peruvian cocoa and have some of the highest cocoa content on the planet",
  "pairing": "Cohiba: Double Corona LE",
  "productPrice": 10.00,
  "Country of Origin": "Peru",
  "quantity": 1,
}, {
  "listing_id": 0014,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/carrot_cake_muffin.jpg'>",
  "productThumb": "<img src='images/thumbs/carrot_cake_muffin.jpg'>",
  "productTitle": "Carrot Cake",
  "productDescription": "Carrot Muffins have the look and flavor of a carrot cake only they are in muffin form. The original name for these muffins was 'Morning Muffin Magic' but you may also know them as 'Morning Glory Muffins'. These cinnamon scented muffins are nice and moist and are loaded with flavorful ingredients; things like toasted nuts, sweetened coconut, grated apple, and grated carrots. Although these muffins need no adornment, sometimes I can't resist smearing them with a little cream cheese icing.",
  "pairing": "Macanudo: Churchill Limited",
  "productPrice": 20.00,
  "Country of Origin": "Lichtenstein",
  "quantity": 1,
}, {
  "listing_id": 0015,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/red_velvet.jpg'>",
  "productThumb": "<img src='images/thumbs/red_velvet.jpg'>",
  "productTitle": "Red Velvet",
  "productDescription": "The cake and its original recipe are well known in the United States from New York City's famous Waldorf-Astoria Hotel, which has also given the cake the name Waldorf-Astoria cake. However, it is widely considered a Southern recipe. Traditionally, the cake is iced with a French-style butter roux icing (also called ermine icing), which is very light and fluffy but time-consuming to prepare. Cream cheese frosting and buttercream frosting are variations which have increased in popularity.",
  "pairing": "Montecristo: No 1",
  "productPrice": 20.00,
  "Country of Origin": "Republic of South Carolina",
  "quantity": 1,
}, {
  "listing_id": 0016,
  "category_id": "Muffins",
  "productImage": "<img src='images/store_large/multigrain.jpg'>",
  "productThumb": "<img src='images/thumbs/multigrain.jpg'>",
  "productTitle": "Multigrain",
  "productDescription": "One of my best friends came into town for Thanksgiving and we were going to pick her up at the airport. I knew she’d be hungry so I baked these muffins. Sure enough, her first text when her flight landed was: Hungarian. Which is, of course, how we tell each other we’re hungry. After finding her in the holiday airport traffic behind an Alamo bus she settled into the back seat of our car and ate the muffin. She loved it, and I loved having her back in town. It was a great start to the holiday week.",
  "pairing": "Partagas: No 4",
  "productPrice": 20.00,
  "Country of Origin": "Republic of California",
  "quantity": 1,
}];

var templates = {};

templates.catalogBlock = [
  '<div class="catalogWrapper">',
  '<div class="catalogProductBlock">',
  '<div class="catalogProductBlockImage">',
  '<%= productThumb %>',
  '</div>',
  '<div class="catalogProductBlockInfo">',
  '<div class="catalogProductBlockTitle">',
  '<%= productTitle %>',
  '</div>',
  '<div class="catalogProductBlockPrice">',
  '$<%= productPrice %>',
  '</div>',
  '</div>',
  '</div>',
  '<div class="catalogProductAddToCartBlock">',
  '<button id="catalogAddToCartButton">Add To Cart</button>',
  '</div>',
  '</div>'
].join("");

templates.productPage = [
  '<div id="productPageTitle">',
    '<h2><%= productTitle %></h2>',
  '</div>',
  '<div id="productPageContent">',
    '<div id="productPageLeft">',
      '<div id="productPageImageBlock">',
        '<%= productImage %>',
      '</div>',
      '<div id="productPagePairingBlock">',
      '<h4>Pairs well with</h4>',
      '<div id="productPagePairingImage">',
      '</div>',
      '</div>',
    '</div>',
    '<div id="productPageRight">',
      '<div id="productPageRightBlock">',
        '<div id="productDescriptionBlock">',
          '<%= productDescription %>',
        '</div>',
        '<div id="productPriceBlock">',
          '$<%= productPrice %>',
        '</div>',
        '<div id="productCartBlock">',
          '<button id="productAddToCartButton">Add To Cart<div id="cartPlusOne">+1</div></button>',
        '</div>',
        '<div id="productCartBlock">',
          '<button id="productContinueShoppingButton">Continue Shopping</button>',
        '</div>',
      '</div>',
    '</div>',
    '<div id="productPageReviews">',
      '<h4>Reviews</h4>',
      '<div id="productReviewsBlock"></div>',
    '</div>',
    '<div id="productReviewsFormBlock">',
      '<form id="productReviewsForm">',
      '<div id="productReviewsFormUsername">',
        'Guest',
      '</div>',
      '<div id="productReviewsFormComment">',
        '<textarea></textarea>',
      '</div>',
      '<div id="productReviewsFormRating">',
        '<select id="productReviewsRatingSelect">',
          '<option selected="selected" value="1">1 Star</option>',
          '<option value="2">2 Stars</option>',
          '<option value="3">3 Stars</option>',
          '<option value="4">4 Stars</option>',
          '<option value="5">5 Stars</option>',
        '</select>',
      '</div>',
      '<div id="productReviewsFormSubmit">',
        '<input type="submit" id="productReviewsSubmitButton">',
      '</div></form>',
    '</div>',
  '</div>'
].join("");

templates.cartItem = [
  '<div class="cartItem" data-id="<%= _id %>">',
    '<div class="cartItemLeft">',
      '<div class="cartItemImage">',
        '<%= productImage %>',
      '</div>',
    '</div>',
    '<div class="cartItemMiddle">',
      '<div class="cartItemTitle">',
        '<%= productTitle %>',
      '</div>',
    '</div>',
    '<div class="cartItemRight">',
      '<div class="cartItemPriceBlock">',
        '$<%= productPrice %>',
      '</div>',
      '<div class="cartItemDeleteBlock">',
        '<div class="cartItemDelete">',
          '<i class="fa fa-times"></i>',
        '</div>',
      '</div>',
    '</div>',
  '</div>'
].join("");

templates.headerRightBlock = [
  '<div id="headerRightBlock2Inner">',
    '<div id="usernameBlock">',
      '<%= username %>',
    '</div>',
    '<div id="cartBlock">',
      '<div id="cartBlockImage">',
        '<i class="fa fa-shopping-cart"></i>',
      '</div>',
      '<div id="cartBlockAmount">',
        '<%= cartAmount %>',
      '</div>',
    '</div>',
  '</div>'
].join("");

templates.productReview = [
  '<div class="productReview">',
    '<div class="productReviewContent">',
      '<%= reviewContent %>',
    '</div>',
    '<div class="reviewBottom">',
      '<div class="productReviewRating">',
      '<% for (var i = 1; i <= reviewRating; i++) { %>',
      '<i class="fa fa-star"></i>',
      '<% } %>',
      '</div>',
      '<div class="productReviewAuthor">',
        '- <%= reviewAuthor %>',
      '</div>',
    '</div>',
  '</div>'
].join("");
